# Generated by Django 5.2.17 on 2026-08-31 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composer', '0019_merge_20260630_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='attachments',
            field=models.JSONField(blank=True, default=list, help_text='Lampiran file dan tautan dokumen eksternal (GDrive, GDocs, dll.)'),
        ),
    ]
