# Generated by Django 5.2.17 on 2026-08-31 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composer', '0020_idea_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='related_idea',
            field=models.ForeignKey(blank=True, help_text='Ide / Brief naskah acuan asal postingan ini dibuat', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_posts', to='composer.idea'),
        ),
    ]
