# Generated by Django 5.2.17 on 2026-09-04 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composer', '0021_post_related_idea'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='attachments',
            field=models.JSONField(blank=True, default=list, help_text='Lampiran file dan tautan dokumen eksternal (GDrive, GDocs, dll.)'),
        ),
    ]
