module.exports = {
  apps: [
    {
      name: 'django-api',
      cwd: './backend',
      script: './venv/bin/gunicorn',
      args: 'config.wsgi:application --bind 127.0.0.1:8000 --workers 3 --threads 2 --timeout 120',
      interpreter: 'none',
      env: {
        DJANGO_SETTINGS_MODULE: 'config.settings.production',
        PYTHONUNBUFFERED: '1',
      },
      autorestart: true,
      max_memory_restart: '500M',
      max_restarts: 10,
      restart_delay: 2000,
      error_file: './logs/pm2/django-api-err.log',
      out_file: './logs/pm2/django-api-out.log',
    },
    {
      name: 'django-worker',
      cwd: './backend',
      script: 'manage.py',
      args: 'process_tasks --duration 0 --sleep 15',
      interpreter: './venv/bin/python',
      env: {
        DJANGO_SETTINGS_MODULE: 'config.settings.production',
        PYTHONUNBUFFERED: '1',
      },
      autorestart: true,
      max_memory_restart: '500M',
      max_restarts: 10,
      restart_delay: 2000,
      error_file: './logs/pm2/django-worker-err.log',
      out_file: './logs/pm2/django-worker-out.log',
    },
    {
      name: 'nextjs-frontend',
      cwd: './frontend',
      script: 'node_modules/next/dist/bin/next',
      args: 'start -p 3000',
      interpreter: 'none',
      env: {
        NODE_ENV: 'production',
        PORT: 3000,
        NEXT_PUBLIC_API_URL: 'http://127.0.0.1:8000',
      },
      autorestart: true,
      max_memory_restart: '600M',
      max_restarts: 10,
      restart_delay: 2000,
      error_file: './logs/pm2/nextjs-frontend-err.log',
      out_file: './logs/pm2/nextjs-frontend-out.log',
    },
  ],
};
