# Generated by Django on 2026-08-28

import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("calendar", "0005_alter_customcalendarevent_color"),
        ("workspaces", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ShootingSession",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="", help_text="Konsep, brief, skrip, atau catatan produksi.")),
                ("location", models.CharField(blank=True, default="", help_text="Lokasi shooting (studio/outdoor).", max_length=255)),
                ("scheduled_at", models.DateTimeField(db_index=True)),
                ("end_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Rencana"),
                            ("confirmed", "Terkonfirmasi"),
                            ("in_progress", "Sedang Berlangsung"),
                            ("completed", "Selesai Shooting"),
                            ("cancelled", "Dibatalkan"),
                        ],
                        db_index=True,
                        default="planned",
                        max_length=30,
                    ),
                ),
                ("crew_members", models.JSONField(blank=True, default=list)),
                ("equipment_checklist", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_shooting_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shooting_sessions",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "calendar_shooting_session",
                "ordering": ["scheduled_at"],
            },
        ),
    ]
