# Generated by Django 5.0.3 on 2026-08-28 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0006_shootingsession'),
        ('composer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shootingsession',
            name='related_idea',
            field=models.ForeignKey(
                blank=True,
                help_text='Ide dari papan Kanban yang menjadi dasar sesi shooting ini.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='shooting_sessions',
                to='composer.idea',
            ),
        ),
    ]
