# Generated by Django 5.2.17 on 2026-08-31 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0007_shootingsession_related_idea'),
    ]

    operations = [
        migrations.AddField(
            model_name='shootingsession',
            name='attachments',
            field=models.JSONField(blank=True, default=list, help_text='Lampiran file & tautan dokumen eksternal (Call Sheet, GDrive, skrip).'),
        ),
    ]
